# Generated by Django 2.2.5 on 2019-09-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('department', models.CharField(choices=[('full day', 'Full Day'), ('half day', 'Half Day')], default='testing', max_length=15)),
                ('reason', models.CharField(choices=[('full day', 'Full Day'), ('half day', 'Half Day')], default='sick leave', max_length=15)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('leave_type', models.CharField(choices=[('full day', 'Full Day'), ('half day', 'Half Day')], default='full day', max_length=10)),
                ('leave_days', models.CharField(max_length=2)),
                ('phone_number', models.CharField(max_length=10)),
                ('Person_in_charge', models.CharField(max_length=40)),
            ],
        ),
    ]
