# Generated by Django 2.2.5 on 2019-09-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('department', models.CharField(choices=[('testing', 'Testing'), ('developement', 'Developement'), ('others', 'Others')], default='testing', max_length=15)),
                ('reason', models.CharField(choices=[('sick leave', 'Sick Leave'), ('casual leave', 'Casual Leave'), ('personal', 'Personal'), ('others', 'Others')], default='sick leave', max_length=15)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('leave_type', models.CharField(choices=[('full day', 'Full Day'), ('half day', 'Half Day')], default='full day', max_length=10)),
                ('leave_days', models.CharField(default='1', max_length=2)),
                ('phone_number', models.CharField(max_length=10)),
                ('Person_in_charge', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='LeaveForm',
        ),
    ]
