# Generated by Django 2.2.5 on 2019-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190923_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.DateField(),
        ),
    ]
