# Generated by Django 2.2.5 on 2019-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190923_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
