# Generated by Django 2.2.5 on 2019-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190923_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateField(blank=True, default='2019-09-24', null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.DateField(blank=True, default='2019-09-24', null=True),
        ),
    ]
