# Generated by Django 2.2.5 on 2019-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190924_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
